Layout
re-pe/simul-doc-fe pull request #9
Opened 2018-06-05 14:28 UTC by re-pe

2018-06-05 15:58 UTC, ralekna requested changes

2018-06-05 15:58 UTC, ralekna commented on .vscode/launch.json
> +{
I think that this file should be kept in .gitignore

2018-06-05 15:58 UTC, ralekna commented on src/components/documents/DocumentEditor.js
> +        <TextField
Why did you leave those fields as text field?

2018-06-05 15:58 UTC, ralekna commented on src/components/documents/DocumentEditor.js
> +          className={classes.textField}
I think that this styling practice is meant to be used for those components that will be reused many times, even in other projects. I really doubt that you will reuse it but it will definitely create a messy markup.

2018-06-05 15:58 UTC, ralekna commented on src/js/constants/constants.js
> +export const FOOTER_HEIGHT = '50px';
These should really be in .css file

2018-06-05 15:58 UTC, ralekna commented on src/components/documents/EditorPage.js
> +    height: `calc(100% - ${HEADER_HEIGHT} - ${FOOTER_HEIGHT})`,
This can be automatically computed by CSS by using flex layout.

2018-06-08 08:34 UTC, re-pe commented on .vscode/launch.json
> +{
Done

2018-06-08 11:18 UTC, ralekna approved these changes
Looks good, merge

2018-06-08 11:23 UTC, merged